Monorepo microservices pipeline

diff --git a/.github/workflows/21_monorepo_microservices_pipeline.yml b/.github/workflows/21_monorepo_microservices_pipeline.yml
--- a/.github/workflows/21_monorepo_microservices_pipeline.yml
+++ b/.github/workflows/21_monorepo_microservices_pipeline.yml
@@ -10,7 +10,6 @@ on:
 jobs:
 
   detect-changes:
-
     runs-on: ubuntu-latest
 
     outputs:
@@ -25,15 +24,19 @@ jobs:
         id: services
         run: |
 
-          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^services/' | cut -d/ -f2 | sort -u)
+          if [ "${{ github.event_name }}" = "push" ]; then
+            CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^services/' | cut -d/ -f2 | sort -u)
+          else
+            CHANGED=$(ls services)
+          fi
 
           if [ -z "$CHANGED" ]; then
-            echo "No service changes detected"
-            MATRIX='{"service":["auth-service","payment-service","order-service"]}'
+            SERVICES=$(ls services)
           else
-            SERVICES=$(printf '"%s",' $CHANGED | sed 's/,$//')
-            MATRIX="{\"service\":[${SERVICES}]}"
+            SERVICES=$CHANGED
           fi
+
+          MATRIX=$(printf '%s\n' "$SERVICES" | jq -R . | jq -s '{service: .}')
 
           echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
           echo "Detected services: $MATRIX"
@@ -41,7 +44,6 @@ jobs:
 
 
   build-services:
-
     runs-on: ubuntu-latest
 
     needs: detect-changes
@@ -54,13 +56,19 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Print Service
-        run: |
-          echo "Building service: ${{ matrix.service }}"
+      - name: Show Repo Structure
+        run: ls -R
 
       - name: Build Docker Image
         run: |
-          docker build -t ${{ matrix.service }} ./services/${{ matrix.service }}
+          SERVICE_PATH="./services/${{ matrix.service }}"
+
+          if [ ! -d "$SERVICE_PATH" ]; then
+            echo "Service not found: $SERVICE_PATH"
+            exit 1
+          fi
+
+          docker build -t ${{ matrix.service }} $SERVICE_PATH
 
       - name: List Docker Images
         run: docker images
@@ -78,6 +86,19 @@ jobs:
 
     steps:
 
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.11
+
+      - name: Install Dependencies
+        run: |
+          pip install pytest
+          pip install -r services/${{ matrix.service }}/requirements.txt
+
       - name: Run Tests
         run: |
-          echo "Running tests for ${{ matrix.service }}"
+          pytest services/${{ matrix.service }}
